[max_node_count.py]
  [test_several_context_nodes]
    expected: FAIL
