[exception_details.py]
  [test_exception_details[[1, 2\][Symbol.iterator\]()-expected28\]]
    expected: FAIL

  [test_exception_details['mystring'[Symbol.iterator\]()-expected29\]]
    expected: FAIL
