[delta.py]
  [test_navigate_special_protocols[data url\]]
    expected: FAIL
