[invalid.py]
  [test_params_context_invalid_type[None\]]
    expected: FAIL

  [test_params_context_invalid_type[False\]]
    expected: FAIL

  [test_params_context_invalid_type[42\]]
    expected: FAIL

  [test_params_context_invalid_type[value3\]]
    expected: FAIL

  [test_params_context_invalid_type[value4\]]
    expected: FAIL

  [test_invalid_frame]
    expected: FAIL

  [test_closed_frame]
    expected: FAIL
