[user_context.py]
  expected: TIMEOUT
