[console.py]
  [test_different_contexts]
    expected: FAIL
