[exception_details.py]
  [test_exception_details[null-expected1-True\]]
    expected: FAIL

  [test_exception_details[null-expected1-False\]]
    expected: FAIL
