[exception_details.py]
  [test_exception_details[([1, 2\][Symbol.iterator\]())-expected28-True\]]
    expected: FAIL

  [test_exception_details[([1, 2\][Symbol.iterator\]())-expected28-False\]]
    expected: FAIL

  [test_exception_details[(function*() { yield 'a'; })()-expected30-True\]]
    expected: FAIL

  [test_exception_details[(function*() { yield 'a'; })()-expected30-False\]]
    expected: FAIL
